version: '3.8'
services:
  dev-db: # name 
    image: postgres:13 # using relational database postgres v 13
    ports:
      - 5434:5432 # going to export to port 5434 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - sufiyan
networks:
  sufiyan: